export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const CLEAR_TASK = 'CLEAR_TASK';
export const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
export const SET_FILTER = 'SET_FILTER';
